qdrant:
  image: qdrant/qdrant
  storagePath: /home/sheraz/ai-ops-copilot/qdrant_storage
ollama:
  image: ollama/ollama
  modelsPath: /usr/share/ollama/.ollama
mcpServer:
  image: ai-ops-copilot-mcp-server
  tag: 3f52779
agent:
  image: ai-ops-copilot-agent
  tag: 3f52779
  apiKey: "7511cbe447693462008585d9af2fb10a3467b33923bf0f32"
operator:
  image: ai-ops-copilot-operator
  tag: 3f52779
