qdrant:
  image: qdrant/qdrant
  storagePath: /home/sheraz/ai-ops-copilot/qdrant_storage

ollama:
  image: ollama/ollama
  modelsPath: /usr/share/ollama/.ollama

mcpServer:
  image: ai-ops-copilot-mcp-server
  tag: latest

agent:
  image: ai-ops-copilot-agent
  tag: latest

operator:
  image: ai-ops-copilot-operator
  tag: latest
