apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-ops-copilot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sh3r4zhassan/ai-ops-copilot.git
    targetRevision: main
    path: charts/ai-ops-copilot
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
