apiVersion: v1
kind: ServiceAccount
metadata:
  name: weekly-summary-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weekly-summary-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weekly-summary-role-binding
subjects:
  - kind: ServiceAccount
    name: weekly-summary-sa
    namespace: default
roleRef:
  kind: Role
  name: weekly-summary-role
  apiGroup: rbac.authorization.k8s.io
