apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-operator
spec:
  replicas: 1
  selector:
    matchLabels: { app: incident-operator }
  template:
    metadata:
      labels: { app: incident-operator }
    spec:
      serviceAccountName: aiops-sa
      containers:
        - name: incident-operator
          image: ai-ops-copilot-operator:latest
          imagePullPolicy: Never
          env:
            - name: AGENT_URL
              value: http://agent:5000/diagnose
